apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 872063250444.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newName: 872063250444.dkr.ecr.ap-southeast-1.amazonaws.com/demo-frontend
  newTag: 490e406a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
